//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_zaklep
    {
        public long id { get; set; }
        public string ip { get; set; }
        public System.DateTime zaklep_do { get; set; }
        public long upirabnik_id { get; set; }
    
        public virtual uporabnik uporabnik { get; set; }
    }
}
