//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class izpitnirok
    {
        public izpitnirok()
        {
            this.prijavanaizpits = new HashSet<prijavanaizpit>();
        }
    
        public int id { get; set; }
        public System.DateTime datum { get; set; }
        public long izvajanjeId { get; set; }
        public Nullable<System.DateTime> ura { get; set; }
        public Nullable<int> prostorId { get; set; }
        public bool fiktiven { get; set; }
    
        public virtual sifrant_prostor sifrant_prostor { get; set; }
        public virtual ICollection<prijavanaizpit> prijavanaizpits { get; set; }
        public virtual izvajanje izvajanje { get; set; }
    }
}
