//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modul
    {
        public modul()
        {
            this.predmets = new HashSet<predmet>();
        }
    
        public long id { get; set; }
        public string ime { get; set; }
    
        public virtual ICollection<predmet> predmets { get; set; }
    }
}
