//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_users
    {
        public my_aspnet_users()
        {
            this.ip_lock = new HashSet<ip_lock>();
            this.my_aspnet_roles = new HashSet<my_aspnet_roles>();
            this.password_recovery = new HashSet<password_recovery>();
            this.students = new HashSet<student>();
            this.kandidats = new HashSet<kandidat>();
            this.prijavanaizpits = new HashSet<prijavanaizpit>();
            this.prijavanaizpits1 = new HashSet<prijavanaizpit>();
            this.profesors = new HashSet<profesor>();
        }
    
        public int id { get; set; }
        public int applicationId { get; set; }
        public string name { get; set; }
        public bool isAnonymous { get; set; }
        public Nullable<System.DateTime> lastActivityDate { get; set; }
    
        public virtual ICollection<ip_lock> ip_lock { get; set; }
        public virtual my_aspnet_applications my_aspnet_applications { get; set; }
        public virtual my_aspnet_membership my_aspnet_membership { get; set; }
        public virtual ICollection<my_aspnet_roles> my_aspnet_roles { get; set; }
        public virtual ICollection<password_recovery> password_recovery { get; set; }
        public virtual ICollection<student> students { get; set; }
        public virtual ICollection<kandidat> kandidats { get; set; }
        public virtual ICollection<prijavanaizpit> prijavanaizpits { get; set; }
        public virtual ICollection<prijavanaizpit> prijavanaizpits1 { get; set; }
        public virtual ICollection<profesor> profesors { get; set; }
    }
}
