//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ocena
    {
        public int id { get; set; }
        public long predmetId { get; set; }
        public int studentId { get; set; }
        public int ocena1 { get; set; }
        public int vpisId { get; set; }
    
        public virtual predmet predmet { get; set; }
        public virtual student student { get; set; }
        public virtual vpi vpi { get; set; }
    }
}
