//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class password_recovery
    {
        public int id { get; set; }
        public int userId { get; set; }
        public System.DateTime valid_until { get; set; }
        public string token { get; set; }
    
        public virtual my_aspnet_users my_aspnet_users { get; set; }
    }
}
