//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;

    public partial class prijavanaizpit
    {
        public prijavanaizpit()
        {
            this.ocenas = new HashSet<ocena>();
            this.tockes = new HashSet<tocke>();
        }
    
        public long id { get; set; }
        public int vpisId { get; set; }
        public int izpitnirokId { get; set; }

        //Stanje 0: študent je prijavljen na izpit
        //Stanje 1: študent se je odjavil od izpita
        //Stanje 2: študent je pisal izpit
        //Stanje 3: študent ni pisal izpita
        //Stanje 4: vrnjena prijava
        public int stanje { get; set; }
        public System.DateTime datumPrijave { get; set; }
        public Nullable<System.DateTime> datumOdjave { get; set; }
        public Nullable<int> odjavilId { get; set; }
        public int prijavilId { get; set; }
    
        public virtual izpitnirok izpitnirok { get; set; }
        public virtual ICollection<ocena> ocenas { get; set; }
        public virtual vpi vpi { get; set; }
        public virtual ICollection<tocke> tockes { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
    }
}
