//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor
    {
        public profesor()
        {
            this.izvajanjes = new HashSet<izvajanje>();
            this.izvajanjes1 = new HashSet<izvajanje>();
            this.izvajanjes2 = new HashSet<izvajanje>();
        }
    
        public long id { get; set; }
        public string ime { get; set; }
        public string priimek { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual ICollection<izvajanje> izvajanjes { get; set; }
        public virtual ICollection<izvajanje> izvajanjes1 { get; set; }
        public virtual ICollection<izvajanje> izvajanjes2 { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
    }
}
