//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sifrant_prostor
    {
        public sifrant_prostor()
        {
            this.izpitniroks = new HashSet<izpitnirok>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<izpitnirok> izpitniroks { get; set; }
    }
}
