using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace studis.Models
{
    public static class Sifranti
    {
        public static readonly Sifrant[] KLASIUS = {
            new Sifrant(12001, "Osnovnošolska izobrazba"),
            new Sifrant(13001, "Nižja poklicna izobrazba"),
            new Sifrant(14001, "Srednja poklicna izobrazba"),
            new Sifrant(15001, "Srednja strokovna izobrazba"),
            new Sifrant(15001, "Srednja splošna izobrazba"),
            new Sifrant(16102, "Višješolska izobrazba (predbolonjska)"),
            new Sifrant(16201, "Specialializacija po visokošolski izobrazbi (predbolonjska)"),
            new Sifrant(16202, "Visokošolska strokovna izobrazba (predbolonjska)"),
            new Sifrant(17001, "Specialializacija po visokošolski strokovni izobrazbi (predbolonjska)"),
            new Sifrant(17002, "Visokošolska univerzitetna izobrazba (predbolonjska)"),
            new Sifrant(18101, "Specialializacija po univerzitetni izobrazbi (predbolonjska)"),
            new Sifrant(18102, "Magisterij znanosti (predbolonjska)"),
            new Sifrant(18201, "Doktorat znanosti (predbolonjska)"),
            new Sifrant(16101, "Višja strokovna izobrazba"),
            new Sifrant(16203, "Visokošolska strokovna izobrazba (prva bolonjska stopnja)"),
            new Sifrant(16204, "Visokošolska univerzitetna izobrazba (prva bolonjska stopnja)"),
            new Sifrant(17003, "Magistrska izobrazba (druga bolonjska stopnja)"),
            new Sifrant(18202, "Doktorat znanosti (tretja bolonjska stopnja)"),
        };

        public static readonly Sifrant[] VRSTAVPISA = {
            new Sifrant(01, "Prvi vpis v letnik/dodatno leto"),
            new Sifrant(02, "Ponavljanje letnika"),
            new Sifrant(03, "Nadaljevanje letnika"),
            new Sifrant(04, "Podaljšanje statusa študenta"),
            new Sifrant(05, "Vpis po merilih za prehode v višji letnik"),
            new Sifrant(06, "Vpis v semester skupnega št. programa"),
            new Sifrant(07, "Vpis po merilih za prehode v isti letnik"),
            new Sifrant(98, "Vpis za zaključek"),
        };

        public static readonly Sifrant[] NACINSTUDIJA = {
            new Sifrant(1, "redni"),
            new Sifrant(3, "izredni"),
        };

        public static readonly Sifrant[] OBLIKASTUDIJA = {
            new Sifrant(1, "na lokaciji"),
            new Sifrant(2, "na daljavo"),
            new Sifrant(3, "e-študij"),
        };

        public static readonly Sifrant[] STUDIJSKIPROGRAM = {
            new Sifrant(1000666, "Humanistika in družb. - DR III"),
            new Sifrant(1000479, "INF. SISTEMI IN ODLOČANJE - DR"),
            new Sifrant(1000480, "INFORMAC. SISTEMI IN ODLOČANJE"),
            new Sifrant(1000472, "Kognitivna znanaost MAG II. st."),
            new Sifrant(1001001, "Multimedija UN 1.st."),
            new Sifrant(1000977, "PEDAGOŠKO RAČ. IN INF. MAG-II. st."),
            new Sifrant(1000667, "Predmetnik za tuje študente na izmenjavi"),
            new Sifrant(1000475, "RAČUNAL. IN INFORMATIKA UN"),
            new Sifrant(1000425, "RAČUNAL. IN MATEMATIKA UN"),
            new Sifrant(1000477, "RAČUNAL. IN INFORMATIKA VS"),
            new Sifrant(1000407, "RAČUNAL. IN MATEMA. UN-I. ST."),
            new Sifrant(1000471, "RAČUNALN. IN INFORM. MAG II. ST."),
            new Sifrant(1000468, "RAČUNALN. IN INFORM. UN-I. ST."),
            new Sifrant(1000470, "RAČUNALN. IN INFORM. VS-I. ST."),
            new Sifrant(1000474, "RAČUNALNIŠ. IN INF. DR-III. ST."),
            new Sifrant(1000478, "RAČUNALNIŠTVO IN INF. - DR"),
            new Sifrant(1000481, "RAČUNALNIŠTVO IN INF. - MAG"),
            new Sifrant(1000668, "RAČUNALNIŠTVO IN INF. - VIS"),
            new Sifrant(1000669, "RAČUNALNIŠTVO IN INF. - VŠ"),
            new Sifrant(1000934, "Računalništvo in matematika MAG II. st."),
            new Sifrant(1000469, "Upravna infromatika UN 1. st"),    
        };

        public static readonly Sifrant[] SPOL = {
            new Sifrant(0, "Moški"),
            new Sifrant(1, "Ženski"),
        };

        public static readonly Sifrant[] LETNIK = {
            new Sifrant(1, "Prvi"),
            new Sifrant(2, "Drugi"),
            new Sifrant(3, "Tretji"),
            new Sifrant(4, "Četrti"),
            new Sifrant(5, "Peti"),
            new Sifrant(6, "Šesti"),
            new Sifrant(0, "Dodatno leto"),
        };

        public static readonly Sifrant[] IZBIRNASKUPINA = {
            new Sifrant(0, "Dopoldanska"),
            new Sifrant(1, "Popoldanska"),
        };

        public static readonly Sifrant[] STUDIJSKOLETO = {
            new Sifrant(0, "/"),
            new Sifrant(1991, "1991/1992"),
            new Sifrant(1992, "1992/1993"),
            new Sifrant(1993, "1993/1994"),
            new Sifrant(1994, "1994/1995"),
            new Sifrant(1995, "1995/1996"),
            new Sifrant(1996, "1996/1997"),
            new Sifrant(1997, "1997/1998"),
            new Sifrant(1998, "1998/1999"),
            new Sifrant(1999, "1999/2000"),
            new Sifrant(2000, "2000/2001"),
            new Sifrant(2001, "2001/2002"),
            new Sifrant(2002, "2002/2003"),
            new Sifrant(2003, "2003/2004"),
            new Sifrant(2004, "2004/2005"),
            new Sifrant(2005, "2005/2006"),
            new Sifrant(2006, "2006/2007"),
            new Sifrant(2007, "2007/2008"),
            new Sifrant(2008, "2008/2009"),
            new Sifrant(2009, "2009/2010"),
            new Sifrant(2010, "2010/2011"),
            new Sifrant(2011, "2011/2012"),
            new Sifrant(2012, "2012/2013"),
            new Sifrant(2013, "2013/2014"),
            new Sifrant(2014, "2014/2015"),
            new Sifrant(2015, "2015/2016"),
            new Sifrant(2016, "2016/2017"),
        };

        public static readonly Sifrant[] DRZAVE = {
            new Sifrant(004, "Afganistan"),
            new Sifrant(008, "Albanija"),
            new Sifrant(010, "Antarktika"),
            new Sifrant(012, "Alžirija"),
            new Sifrant(016, "Ameriška Samoa"),
            new Sifrant(020, "Andora"),
            new Sifrant(024, "Angola"),
            new Sifrant(028, "Antigva in Barbuda"),
            new Sifrant(031, "Azerbajdžan"),
            new Sifrant(032, "Argentina"),
            new Sifrant(036, "Avstralija"),
            new Sifrant(040, "Avstrija"),
            new Sifrant(044, "Bahami"),
            new Sifrant(048, "Bahrajn"),
            new Sifrant(050, "Bangladeš"),
            new Sifrant(051, "Armenija"),
            new Sifrant(052, "Barbados"),
            new Sifrant(056, "Belgija"),
            new Sifrant(060, "Bermudi"),
            new Sifrant(064, "Butan"),
            new Sifrant(068, "Bolivija"),
            new Sifrant(070, "Bosna in Hercegovina"),
            new Sifrant(072, "Bocvana"),
            new Sifrant(074, "Bouvetov otok"),
            new Sifrant(076, "Brazilija"),
            new Sifrant(084, "Belize"),
            new Sifrant(086, "Britansko ozemlje Indijskega oceana"),
            new Sifrant(090, "Salomonovi otoki"),
            new Sifrant(092, "Deviški otoki (britanski)"),
            new Sifrant(096, "Brunej, Država"),
            new Sifrant(100, "Bolgarija"),
            new Sifrant(104, "Mjanmar"),
            new Sifrant(108, "Burundi"),
            new Sifrant(112, "Belorusija"),
            new Sifrant(116, "Kambodža"),
            new Sifrant(120, "Kamerun"),
            new Sifrant(124, "Kanada"),
            new Sifrant(132, "Zelenortski otoki"),
            new Sifrant(136, "Kajmanski otoki"),
            new Sifrant(140, "Srednjeafriška republika"),
            new Sifrant(144, "Šrilanka"),
            new Sifrant(148, "Čad"),
            new Sifrant(152, "Čile"),
            new Sifrant(156, "Kitajska"),
            new Sifrant(158, "Tajvan, Provinca Kitajske"),
            new Sifrant(162, "Božični otok"),
            new Sifrant(166, "Kokosovi (Keeling) otoki"),
            new Sifrant(170, "Kolumbija"),
            new Sifrant(174, "Komori"),
            new Sifrant(175, "Mayotte"),
            new Sifrant(178, "Kongo"),
            new Sifrant(180, "Kongo, Demokratična republika"),
            new Sifrant(184, "Cookovi otoki"),
            new Sifrant(188, "Kostarika"),
            new Sifrant(191, "Hrvaška"),
            new Sifrant(192, "Kuba"),
            new Sifrant(196, "Ciper"),
            new Sifrant(203, "Češka republika"),
            new Sifrant(204, "Benin"),
            new Sifrant(208, "Danska"),
            new Sifrant(212, "Dominika"),
            new Sifrant(214, "Dominikanska republika"),
            new Sifrant(218, "Ekvador"),
            new Sifrant(222, "Salvador"),
            new Sifrant(226, "Ekvatorialna Gvineja"),
            new Sifrant(231, "Etiopija"),
            new Sifrant(232, "Eritreja"),
            new Sifrant(233, "Estonija"),
            new Sifrant(234, "Ferski otoki"),
            new Sifrant(238, "Falklandski otoki (Malvini)"),
            new Sifrant(239, "Južna Georgia in otoki Južni Sandwich"),
            new Sifrant(242, "Fidži"),
            new Sifrant(246, "Finska"),
            new Sifrant(248, "Alandski otoki"),
            new Sifrant(250, "Francija"),
            new Sifrant(254, "Francoska Gvajana"),
            new Sifrant(258, "Francoska Polinezija"),
            new Sifrant(260, "Francosko južno ozemlje"),
            new Sifrant(262, "Džibuti"),
            new Sifrant(266, "Gabon"),
            new Sifrant(268, "Gruzija"),
            new Sifrant(270, "Gambija"),
            new Sifrant(275, "Palestinsko ozemlje, zasedeno"),
            new Sifrant(276, "Nemčija"),
            new Sifrant(288, "Gana"),
            new Sifrant(292, "Gibraltar"),
            new Sifrant(296, "Kiribati"),
            new Sifrant(300, "Grčija"),
            new Sifrant(304, "Grenlandija"),
            new Sifrant(308, "Grenada"),
            new Sifrant(312, "Guadeloupe"),
            new Sifrant(316, "Guam"),
            new Sifrant(320, "Gvatemala"),
            new Sifrant(324, "Gvineja"),
            new Sifrant(328, "Gvajana"),
            new Sifrant(332, "Haiti"),
            new Sifrant(334, "Heardov otok in McDonaldovi otoki"),
            new Sifrant(336, "Sveti sedež (Vatikanska mestna država)"),
            new Sifrant(340, "Honduras"),
            new Sifrant(344, "Hongkong"),
            new Sifrant(348, "Madžarska"),
            new Sifrant(352, "Islandija"),
            new Sifrant(356, "Indija"),
            new Sifrant(360, "Indonezija"),
            new Sifrant(364, "Iran (Islamska republika)"),
            new Sifrant(368, "Irak"),
            new Sifrant(372, "Irska"),
            new Sifrant(376, "Izrael"),
            new Sifrant(380, "Italija"),
            new Sifrant(384, "Slonokoščena obala"),
            new Sifrant(388, "Jamajka"),
            new Sifrant(392, "Japonska"),
            new Sifrant(398, "Kazahstan"),
            new Sifrant(400, "Jordanija"),
            new Sifrant(404, "Kenija"),
            new Sifrant(408, "Koreja, Demokratična ljudska republika"),
            new Sifrant(410, "Koreja, Republika"),
            new Sifrant(414, "Kuvajt"),
            new Sifrant(417, "Kirgizistan"),
            new Sifrant(418, "Laoška ljudska demokratična republika"),
            new Sifrant(422, "Libanon"),
            new Sifrant(426, "Lesoto"),
            new Sifrant(428, "Latvija"),
            new Sifrant(430, "Liberija"),
            new Sifrant(434, "Libijska arabska džamahirija"),
            new Sifrant(438, "Lihtenštajn"),
            new Sifrant(440, "Litva"),
            new Sifrant(442, "Luksemburg"),
            new Sifrant(446, "Macau"),
            new Sifrant(450, "Madagaskar"),
            new Sifrant(454, "Malavi"),
            new Sifrant(458, "Malezija"),
            new Sifrant(462, "Maldivi"),
            new Sifrant(466, "Mali"),
            new Sifrant(470, "Malta"),
            new Sifrant(474, "Martinik"),
            new Sifrant(478, "Mavretanija"),
            new Sifrant(480, "Mauritius"),
            new Sifrant(484, "Mehika"),
            new Sifrant(492, "Monako"),
            new Sifrant(496, "Mongolija"),
            new Sifrant(498, "Moldavija, Republika"),
            new Sifrant(499, "Črna Gora"),
            new Sifrant(500, "Montserrat"),
            new Sifrant(504, "Maroko"),
            new Sifrant(508, "Mozambik"),
            new Sifrant(512, "Oman"),
            new Sifrant(516, "Namibija"),
            new Sifrant(520, "Nauru"),
            new Sifrant(524, "Nepal"),
            new Sifrant(528, "Nizozemska"),
            new Sifrant(530, "Nizozemski Antili"),
            new Sifrant(533, "Aruba"),
            new Sifrant(540, "Nova Kaledonija"),
            new Sifrant(548, "Vanuatu"),
            new Sifrant(554, "Nova Zelandija"),
            new Sifrant(558, "Nikaragva"),
            new Sifrant(562, "Niger"),
            new Sifrant(566, "Nigerija"),
            new Sifrant(570, "Niue"),
            new Sifrant(574, "Norfolški otok"),
            new Sifrant(578, "Norveška"),
            new Sifrant(580, "Severni Marianski otoki"),
            new Sifrant(581, "Stranski zunanji otoki Združenih držav"),
            new Sifrant(583, "Mikronezija (Federativne države)"),
            new Sifrant(584, "Marshallovi otoki"),
            new Sifrant(585, "Palau"),
            new Sifrant(586, "Pakistan"),
            new Sifrant(591, "Panama"),
            new Sifrant(598, "Papua Nova Gvineja"),
            new Sifrant(600, "Paragvaj"),
            new Sifrant(604, "Peru"),
            new Sifrant(608, "Filipini"),
            new Sifrant(612, "Pitcairn"),
            new Sifrant(616, "Poljska"),
            new Sifrant(620, "Portugalska"),
            new Sifrant(624, "Gvineja Bissau"),
            new Sifrant(626, "Vzhodni Timor"),
            new Sifrant(630, "Portoriko"),
            new Sifrant(634, "Katar"),
            new Sifrant(638, "Reunion"),
            new Sifrant(642, "Romunija"),
            new Sifrant(643, "Ruska federacija"),
            new Sifrant(646, "Ruanda"),
            new Sifrant(654, "Saint Helena"),
            new Sifrant(659, "Saint Kitts in Nevis"),
            new Sifrant(660, "Angvila"),
            new Sifrant(662, "Saint Lucia"),
            new Sifrant(666, "Saint Pierre in Miquelon"),
            new Sifrant(670, "Saint Vincent in Grenadine"),
            new Sifrant(674, "San Marino"),
            new Sifrant(678, "Sao Tome in Principe"),
            new Sifrant(682, "Saudova Arabija"),
            new Sifrant(686, "Senegal"),
            new Sifrant(688, "Srbija"),
            new Sifrant(690, "Sejšeli"),
            new Sifrant(694, "Sierra Leone"),
            new Sifrant(702, "Singapur"),
            new Sifrant(703, "Slovaška"),
            new Sifrant(704, "Vietnam"),
            new Sifrant(705, "Slovenija"),
            new Sifrant(706, "Somalija"),
            new Sifrant(710, "Južna Afrika"),
            new Sifrant(716, "Zimbabve"),
            new Sifrant(724, "Španija"),
            new Sifrant(732, "Zahodna Sahara"),
            new Sifrant(736, "Sudan"),
            new Sifrant(740, "Surinam"),
            new Sifrant(744, "Svalbard in Jan Mayen"),
            new Sifrant(748, "Svazi"),
            new Sifrant(752, "Švedska"),
            new Sifrant(756, "Švica"),
            new Sifrant(760, "Sirska arabska republika"),
            new Sifrant(762, "Tadžikistan"),
            new Sifrant(764, "Tajska"),
            new Sifrant(768, "Togo"),
            new Sifrant(772, "Tokelau"),
            new Sifrant(776, "Tonga"),
            new Sifrant(780, "Trinidad in Tobago"),
            new Sifrant(784, "Združeni arabski emirati"),
            new Sifrant(788, "Tunizija"),
            new Sifrant(792, "Turčija"),
            new Sifrant(795, "Turkmenistan"),
            new Sifrant(796, "Otoki Turks in Caicos"),
            new Sifrant(798, "Tuvalu"),
            new Sifrant(800, "Uganda"),
            new Sifrant(804, "Ukrajina"),
            new Sifrant(807, "Makedonija, Nekdanja jugoslovanska republika"),
            new Sifrant(818, "Egipt"),
            new Sifrant(826, "Združeno kraljestvo"),
            new Sifrant(831, "Guernsey"),
            new Sifrant(832, "Jersey"),
            new Sifrant(833, "Otok Man"),
            new Sifrant(834, "Tanzanija, Združena republika"),
            new Sifrant(840, "Združene države"),
            new Sifrant(850, "Deviški otoki (ZDA)"),
            new Sifrant(854, "Burkina Faso"),
            new Sifrant(858, "Urugvaj"),
            new Sifrant(860, "Uzbekistan"),
            new Sifrant(862, "Venezuela"),
            new Sifrant(876, "Otoki Wallis in Futuna"),
            new Sifrant(882, "Samoa"),
            new Sifrant(887, "Jemen"),
            new Sifrant(894, "Zambija"),
            new Sifrant(999, "NERAZVRŠČENO"),
        };

        public static readonly Sifrant[] OBCINE = {
            new Sifrant(213	, "Ankaran"),
            new Sifrant(1	, "Ajdovščina "),
            new Sifrant(195	, "Apače "),
            new Sifrant(2	, "Beltinci "),
            new Sifrant(148	, "Benedikt "),
            new Sifrant(149	, "Bistrica ob Sotli "),
            new Sifrant(3	, "Bled "),
            new Sifrant(150	, "Bloke "),
            new Sifrant(4	, "Bohinj "),
            new Sifrant(5	, "Borovnica "),
            new Sifrant(6	, "Bovec "),
            new Sifrant(151	, "Braslovče "),
            new Sifrant(7	, "Brda "),
            new Sifrant(8	, "Brezovica "),
            new Sifrant(9	, "Brežice "),
            new Sifrant(152	, "Cankova "),
            new Sifrant(11	, "Celje "),
            new Sifrant(12	, "Cerklje na Gorenjskem "),
            new Sifrant(13	, "Cerknica "),
            new Sifrant(14	, "Cerkno "),
            new Sifrant(153	, "Cerkvenjak "),
            new Sifrant(196	, "Cirkulane "),
            new Sifrant(15	, "Črenšovci "),
            new Sifrant(16	, "Črna na Koroškem "),
            new Sifrant(17	, "Črnomelj "),
            new Sifrant(18	, "Destrnik "),
            new Sifrant(19	, "Divača "),
            new Sifrant(154	, "Dobje "),
            new Sifrant(20	, "Dobrepolje "),
            new Sifrant(155	, "Dobrna "),
            new Sifrant(21	, "Dobrova - Polhov Gradec "),
            new Sifrant(156	, "Dobrovnik "),
            new Sifrant(22	, "Dol pri Ljubljani "),
            new Sifrant(157	, "Dolenjske Toplice "),
            new Sifrant(23	, "Domžale "),
            new Sifrant(24	, "Dornava "),
            new Sifrant(25	, "Dravograd "),
            new Sifrant(26	, "Duplek "),
            new Sifrant(27	, "Gorenja vas - Poljane "),
            new Sifrant(28	, "Gorišnica "),
            new Sifrant(207	, "Gorje "),
            new Sifrant(29	, "Gornja Radgona "),
            new Sifrant(30	, "Gornji Grad "),
            new Sifrant(31	, "Gornji Petrovci "),
            new Sifrant(158	, "Grad "),
            new Sifrant(32	, "Grosuplje "),
            new Sifrant(159	, "Hajdina "),
            new Sifrant(160	, "Hoče - Slivnica "),
            new Sifrant(161	, "Hodoš "),
            new Sifrant(162	, "Horjul "),
            new Sifrant(34	, "Hrastnik "),
            new Sifrant(35	, "Hrpelje - Kozina "),
            new Sifrant(36	, "Idrija "),
            new Sifrant(37	, "Ig "),
            new Sifrant(38	, "Ilirska Bistrica "),
            new Sifrant(39	, "Ivančna Gorica "),
            new Sifrant(40	, "Izola "),
            new Sifrant(41	, "Jesenice "),
            new Sifrant(163	, "Jezersko "),
            new Sifrant(42	, "Juršinci "),
            new Sifrant(43	, "Kamnik "),
            new Sifrant(44	, "Kanal "),
            new Sifrant(45	, "Kidričevo "),
            new Sifrant(46	, "Kobarid "),
            new Sifrant(47	, "Kobilje "),
            new Sifrant(48	, "Kočevje "),
            new Sifrant(49	, "Komen "),
            new Sifrant(164	, "Komenda "),
            new Sifrant(50	, "Koper "),
            new Sifrant(197	, "Kostanjevica na Krki "),
            new Sifrant(165	, "Kostel "),
            new Sifrant(51	, "Kozje "),
            new Sifrant(52	, "Kranj "),
            new Sifrant(53	, "Kranjska Gora "),
            new Sifrant(166	, "Križevci "),
            new Sifrant(54	, "Krško "),
            new Sifrant(55	, "Kungota "),
            new Sifrant(56	, "Kuzma "),
            new Sifrant(57	, "Laško "),
            new Sifrant(58	, "Lenart "),
            new Sifrant(59	, "Lendava "),
            new Sifrant(60	, "Litija "),
            new Sifrant(61	, "Ljubljana "),
            new Sifrant(62	, "Ljubno "),
            new Sifrant(63	, "Ljutomer "),
            new Sifrant(208	, "Log - Dragomer "),
            new Sifrant(64	, "Logatec "),
            new Sifrant(65	, "Loška dolina "),
            new Sifrant(66	, "Loški Potok "),
            new Sifrant(167	, "Lovrenc na Pohorju "),
            new Sifrant(67	, "Luče "),
            new Sifrant(68	, "Lukovica "),
            new Sifrant(69	, "Majšperk "),
            new Sifrant(198	, "Makole "),
            new Sifrant(70	, "Maribor "),
            new Sifrant(168	, "Markovci "),
            new Sifrant(71	, "Medvode "),
            new Sifrant(72	, "Mengeš "),
            new Sifrant(73	, "Metlika "),
            new Sifrant(74	, "Mežica "),
            new Sifrant(169	, "Miklavž na Dravskem polju"),
            new Sifrant(75	, "Miren - Kostanjevica "),
            new Sifrant(212	, "Mirna "),
            new Sifrant(170	, "Mirna Peč "),
            new Sifrant(76	, "Mislinja "),
            new Sifrant(199	, "Mokronog - Trebelno "),
            new Sifrant(77	, "Moravče "),
            new Sifrant(78	, "Moravske Toplice "),
            new Sifrant(79	, "Mozirje "),
            new Sifrant(80	, "Murska Sobota "),
            new Sifrant(81	, "Muta "),
            new Sifrant(82	, "Naklo "),
            new Sifrant(83	, "Nazarje "),
            new Sifrant(84	, "Nova Gorica "),
            new Sifrant(85	, "Novo mesto "),
            new Sifrant(86	, "Odranci "),
            new Sifrant(171	, "Oplotnica "),
            new Sifrant(87	, "Ormož "),
            new Sifrant(88	, "Osilnica "),
            new Sifrant(89	, "Pesnica "),
            new Sifrant(90	, "Piran "),
            new Sifrant(91	, "Pivka "),
            new Sifrant(92	, "Podčetrtek "),
            new Sifrant(172	, "Podlehnik "),
            new Sifrant(93	, "Podvelka "),
            new Sifrant(200	, "Poljčane "),
            new Sifrant(173	, "Polzela "),
            new Sifrant(94	, "Postojna "),
            new Sifrant(174	, "Prebold "),
            new Sifrant(95	, "Preddvor "),
            new Sifrant(175	, "Prevalje "),
            new Sifrant(96	, "Ptuj "),
            new Sifrant(97	, "Puconci "),
            new Sifrant(98	, "Rače - Fram "),
            new Sifrant(99	, "Radeče "),
            new Sifrant(100	, "Radenci "),
            new Sifrant(101	, "Radlje ob Dravi "),
            new Sifrant(102	, "Radovljica "),
            new Sifrant(103	, "Ravne na Koroškem "),
            new Sifrant(176	, "Razkrižje "),
            new Sifrant(209	, "Rečica ob Savinji "),
            new Sifrant(201	, "Renče - Vogrsko "),
            new Sifrant(104	, "Ribnica "),
            new Sifrant(177	, "Ribnica na Pohorju "),
            new Sifrant(106	, "Rogaška Slatina "),
            new Sifrant(105	, "Rogašovci "),
            new Sifrant(107	, "Rogatec "),
            new Sifrant(108	, "Ruše "),
            new Sifrant(178	, "Selnica ob Dravi "),
            new Sifrant(109	, "Semič "),
            new Sifrant(110	, "Sevnica "),
            new Sifrant(111	, "Sežana "),
            new Sifrant(112	, "Slovenj Gradec "),
            new Sifrant(113	, "Slovenska Bistrica "),
            new Sifrant(114	, "Slovenske Konjice "),
            new Sifrant(179	, "Sodražica "),
            new Sifrant(180	, "Solčava "),
            new Sifrant(202	, "Središče ob Dravi "),
            new Sifrant(115	, "Starše "),
            new Sifrant(203	, "Straža "),
            new Sifrant(204	, "Sv. Trojica v Slov. Goricah "),
            new Sifrant(181	, "Sveta Ana "),
            new Sifrant(182	, "Sveti Andraž v Slov. Goricah "),
            new Sifrant(116	, "Sveti Jurij ob Ščavnici "),
            new Sifrant(210	, "Sveti Jurij v Slov. Goricah "),
            new Sifrant(205	, "Sveti Tomaž "),
            new Sifrant(33	, "Šalovci "),
            new Sifrant(183	, "Šempeter - Vrtojba "),
            new Sifrant(117	, "Šenčur "),
            new Sifrant(118	, "Šentilj "),
            new Sifrant(119	, "Šentjernej "),
            new Sifrant(120	, "Šentjur pri Celju "),
            new Sifrant(211	, "Šentrupert "),
            new Sifrant(121	, "Škocjan "),
            new Sifrant(122	, "Škofja Loka "),
            new Sifrant(123	, "Škofljica "),
            new Sifrant(124	, "Šmarje pri Jelšah "),
            new Sifrant(206	, "Šmarješke Toplice "),
            new Sifrant(125	, "Šmartno ob Paki "),
            new Sifrant(194	, "Šmartno pri Litiji "),
            new Sifrant(126	, "Šoštanj "),
            new Sifrant(127	, "Štore "),
            new Sifrant(184	, "Tabor "),
            new Sifrant(10	, "Tišina "),
            new Sifrant(128	, "Tolmin "),
            new Sifrant(129	, "Trbovlje "),
            new Sifrant(130	, "Trebnje "),
            new Sifrant(185	, "Trnovska vas "),
            new Sifrant(186	, "Trzin "),
            new Sifrant(131	, "Tržič "),
            new Sifrant(132	, "Turnišče "),
            new Sifrant(133	, "Velenje "),
            new Sifrant(187	, "Velika Polana "),
            new Sifrant(134	, "Velike Lašče "),
            new Sifrant(188	, "Veržej "),
            new Sifrant(135	, "Videm "),
            new Sifrant(136	, "Vipava "),
            new Sifrant(137	, "Vitanje "),
            new Sifrant(138	, "Vodice "),
            new Sifrant(139	, "Vojnik "),
            new Sifrant(189	, "Vransko "),
            new Sifrant(140	, "Vrhnika "),
            new Sifrant(141	, "Vuzenica "),
            new Sifrant(142	, "Zagorje ob Savi "),
            new Sifrant(143	, "Zavrč "),
            new Sifrant(144	, "Zreče "),
            new Sifrant(190	, "Žalec "),
            new Sifrant(146	, "Železniki "),
            new Sifrant(191	, "Žetale "),
            new Sifrant(147	, "Žiri "),
            new Sifrant(192	, "Žirovnica "),
            new Sifrant(193	, "Žužemberk "),
            new Sifrant(-1, "TUJINA"),
        };

        public static readonly Sifrant[] POSTNESTEVILKE = {
            new Sifrant(8341, "Adlešiči"),
            new Sifrant(5270, "Ajdovščina"),
            new Sifrant(6280, "Ankaran/Ancarano"),
            new Sifrant(9253, "Apače"),
            new Sifrant(8253, "Artiče"),
            new Sifrant(4275, "Begunje na Gorenjskem"),
            new Sifrant(1382, "Begunje pri Cerknici"),
            new Sifrant(9231, "Beltinci"),
            new Sifrant(2234, "Benedikt"),
            new Sifrant(2345, "Bistrica ob Dravi"),
            new Sifrant(3256, "Bistrica ob Sotli"),
            new Sifrant(8259, "Bizeljsko"),
            new Sifrant(1223, "Blagovica"),
            new Sifrant(8283, "Blanca"),
            new Sifrant(4260, "Bled"),
            new Sifrant(4273, "Blejska Dobrava"),
            new Sifrant(9265, "Bodonci"),
            new Sifrant(9222, "Bogojina"),
            new Sifrant(4263, "Bohinjska Bela"),
            new Sifrant(4264, "Bohinjska Bistrica"),
            new Sifrant(4265, "Bohinjsko jezero"),
            new Sifrant(1353, "Borovnica"),
            new Sifrant(8294, "Boštanj"),
            new Sifrant(5230, "Bovec"),
            new Sifrant(5295, "Branik"),
            new Sifrant(3314, "Braslovče"),
            new Sifrant(5223, "Breginj"),
            new Sifrant(8280, "Brestanica"),
            new Sifrant(2354, "Bresternica"),
            new Sifrant(4243, "Brezje"),
            new Sifrant(1351, "Brezovica pri Ljubljani"),
            new Sifrant(8250, "Brežice"),
            new Sifrant(4210, "Brnik - aerodrom"),
            new Sifrant(8321, "Brusnice"),
            new Sifrant(3255, "Buče"),
            new Sifrant(8276, "Bučka"),
            new Sifrant(9261, "Cankova"),
            new Sifrant(3505, "Celje    Merkur "),
            new Sifrant(3600, "Celje    Pošta Slovenije d.o.o., PE Celje "),
            new Sifrant(3000, "Celje"),
            new Sifrant(3001, "Celje"),
            new Sifrant(4207, "Cerklje na Gorenjskem"),
            new Sifrant(8263, "Cerklje ob Krki"),
            new Sifrant(1380, "Cerknica"),
            new Sifrant(5282, "Cerkno"),
            new Sifrant(2236, "Cerkvenjak"),
            new Sifrant(2215, "Ceršak"),
            new Sifrant(2326, "Cirkovce"),
            new Sifrant(2282, "Cirkulane"),
            new Sifrant(5273, "Col"),
            new Sifrant(8251, "Čatež ob Savi"),
            new Sifrant(1413, "Čemšenik"),
            new Sifrant(5253, "Čepovan"),
            new Sifrant(9232, "Črenšovci"),
            new Sifrant(2393, "Črna na Koroškem"),
            new Sifrant(6275, "Črni Kal"),
            new Sifrant(5274, "Črni Vrh nad Idrijo"),
            new Sifrant(5262, "Črniče"),
            new Sifrant(8340, "Črnomelj"),
            new Sifrant(6271, "Dekani"),
            new Sifrant(5210, "Deskle"),
            new Sifrant(2253, "Destrnik"),
            new Sifrant(6215, "Divača"),
            new Sifrant(1233, "Dob"),
            new Sifrant(3224, "Dobje pri Planini"),
            new Sifrant(8257, "Dobova"),
            new Sifrant(1423, "Dobovec"),
            new Sifrant(5263, "Dobravlje"),
            new Sifrant(3204, "Dobrna"),
            new Sifrant(8211, "Dobrnič"),
            new Sifrant(1356, "Dobrova"),
            new Sifrant(9223, "Dobrovnik/Dobronak"),
            new Sifrant(5212, "Dobrovo v Brdih"),
            new Sifrant(1431, "Dol pri Hrastniku"),
            new Sifrant(1262, "Dol pri Ljubljani"),
            new Sifrant(1273, "Dole pri Litiji"),
            new Sifrant(1331, "Dolenja vas"),
            new Sifrant(8350, "Dolenjske Toplice"),
            new Sifrant(1230, "Domžale"),
            new Sifrant(2252, "Dornava"),
            new Sifrant(5294, "Dornberk"),
            new Sifrant(1319, "Draga"),
            new Sifrant(8343, "Dragatuš"),
            new Sifrant(3222, "Dramlje"),
            new Sifrant(2370, "Dravograd"),
            new Sifrant(4203, "Duplje"),
            new Sifrant(6221, "Dutovlje"),
            new Sifrant(8361, "Dvor"),
            new Sifrant(2343, "Fala"),
            new Sifrant(9208, "Fokovci"),
            new Sifrant(2313, "Fram"),
            new Sifrant(3213, "Frankolovo"),
            new Sifrant(1274, "Gabrovka"),
            new Sifrant(8254, "Globoko"),
            new Sifrant(5275, "Godovič"),
            new Sifrant(4204, "Golnik"),
            new Sifrant(3303, "Gomilsko"),
            new Sifrant(4224, "Gorenja vas"),
            new Sifrant(3263, "Gorica pri Slivnici"),
            new Sifrant(2272, "Gorišnica"),
            new Sifrant(9250, "Gornja Radgona"),
            new Sifrant(3342, "Gornji Grad"),
            new Sifrant(4282, "Gozd Martuljek"),
            new Sifrant(6272, "Gračišče"),
            new Sifrant(9264, "Grad"),
            new Sifrant(8332, "Gradac"),
            new Sifrant(1384, "Grahovo"),
            new Sifrant(5242, "Grahovo ob Bači"),
            new Sifrant(5251, "Grgar"),
            new Sifrant(3302, "Griže"),
            new Sifrant(3231, "Grobelno"),
            new Sifrant(1290, "Grosuplje"),
            new Sifrant(2288, "Hajdina"),
            new Sifrant(8362, "Hinje"),
            new Sifrant(2311, "Hoče"),
            new Sifrant(9205, "Hodoš/Hodos"),
            new Sifrant(1354, "Horjul"),
            new Sifrant(1372, "Hotedršica"),
            new Sifrant(1430, "Hrastnik"),
            new Sifrant(6225, "Hruševje"),
            new Sifrant(4276, "Hrušica"),
            new Sifrant(5280, "Idrija"),
            new Sifrant(1292, "Ig"),
            new Sifrant(6250, "Ilirska Bistrica"),
            new Sifrant(6251, "Ilirska Bistrica - Trnovo"),
            new Sifrant(1295, "Ivančna Gorica"),
            new Sifrant(2259, "Ivanjkovci"),
            new Sifrant(1411, "Izlake"),
            new Sifrant(6310, "Izola/Isola"),
            new Sifrant(2222, "Jakobski Dol"),
            new Sifrant(2221, "Jarenina"),
            new Sifrant(6254, "Jelšane"),
            new Sifrant(4270, "Jesenice"),
            new Sifrant(8261, "Jesenice na Dolenjskem"),
            new Sifrant(3273, "Jurklošter"),
            new Sifrant(2223, "Jurovski Dol"),
            new Sifrant(2256, "Juršinci"),
            new Sifrant(5214, "Kal nad Kanalom"),
            new Sifrant(3233, "Kalobje"),
            new Sifrant(4246, "Kamna Gorica"),
            new Sifrant(2351, "Kamnica"),
            new Sifrant(1241, "Kamnik"),
            new Sifrant(5213, "Kanal"),
            new Sifrant(8258, "Kapele"),
            new Sifrant(2362, "Kapla"),
            new Sifrant(2325, "Kidričevo"),
            new Sifrant(1412, "Kisovec"),
            new Sifrant(6253, "Knežak"),
            new Sifrant(5222, "Kobarid"),
            new Sifrant(9227, "Kobilje"),
            new Sifrant(1330, "Kočevje"),
            new Sifrant(1338, "Kočevska Reka"),
            new Sifrant(2276, "Kog"),
            new Sifrant(5211, "Kojsko"),
            new Sifrant(6223, "Komen"),
            new Sifrant(1218, "Komenda"),
            new Sifrant(6501, "Koper - Capodistria    Luka Koper "),
            new Sifrant(6502, "Koper - Capodistria    Banka Koper "),
            new Sifrant(6503, "Koper - Capodistria    Adriatic zavarovalna družba "),
            new Sifrant(6504, "Koper - Capodistria    Intereuropa Koper "),
            new Sifrant(6600, "Koper - Capodistria    Pošta Slovenije d.o.o., PE Koper "),
            new Sifrant(6000, "Koper - Capodistria"),
            new Sifrant(6001, "Koper - Capodistria"),
            new Sifrant(6200, "Koper - Capodistria    Pošta Slovenije d.o.o., PPP Koper "),
            new Sifrant(8282, "Koprivnica"),
            new Sifrant(5296, "Kostanjevica na Krasu"),
            new Sifrant(8311, "Kostanjevica na Krki"),
            new Sifrant(1336, "Kostel"),
            new Sifrant(6256, "Košana"),
            new Sifrant(2394, "Kotlje"),
            new Sifrant(6240, "Kozina"),
            new Sifrant(3260, "Kozje"),
            new Sifrant(4502, "Kranj    Sava "),
            new Sifrant(4600, "Kranj    Pošta Slovenije d.o.o., PE Kranj "),
            new Sifrant(4000, "Kranj"),
            new Sifrant(4001, "Kranj"),
            new Sifrant(4200, "Kranj    Pošta Slovenije d.o.o, PPP Šenčur "),
            new Sifrant(4280, "Kranjska Gora"),
            new Sifrant(1281, "Kresnice"),
            new Sifrant(4294, "Križe"),
            new Sifrant(9206, "Križevci"),
            new Sifrant(9242, "Križevci pri Ljutomeru"),
            new Sifrant(1301, "Krka"),
            new Sifrant(8296, "Krmelj"),
            new Sifrant(4245, "Kropa"),
            new Sifrant(8262, "Krška vas"),
            new Sifrant(8270, "Krško"),
            new Sifrant(9263, "Kuzma"),
            new Sifrant(2318, "Laporje"),
            new Sifrant(3270, "Laško"),
            new Sifrant(1219, "Laze v Tuhinju"),
            new Sifrant(2230, "Lenart v Slovenskih goricah"),
            new Sifrant(9220, "Lendava/Lendva"),
            new Sifrant(4248, "Lesce"),
            new Sifrant(3261, "Lesično"),
            new Sifrant(8273, "Leskovec pri Krškem"),
            new Sifrant(2372, "Libeliče"),
            new Sifrant(2341, "Limbuš"),
            new Sifrant(1270, "Litija"),
            new Sifrant(3202, "Ljubečna"),
            new Sifrant(1000, "Ljubljana"),
            new Sifrant(1001, "Ljubljana"),
            new Sifrant(1501, "Ljubljana    Ministrstvo za notranje zadeve "),
            new Sifrant(1502, "Ljubljana    Ministrstvo za finance "),
            new Sifrant(1503, "Ljubljana    Okrožno sodišče v Ljubljani "),
            new Sifrant(1504, "Ljubljana    Gospodarska zbornica Slovenije "),
            new Sifrant(1505, "Ljubljana    Banka Slovenije "),
            new Sifrant(1506, "Ljubljana    Slovenske železnice "),
            new Sifrant(1507, "Ljubljana    Zavod za zdrav. zav. Slov. "),
            new Sifrant(1509, "Ljubljana    Delo "),
            new Sifrant(1510, "Ljubljana    Dnevnik "),
            new Sifrant(1511, "Ljubljana    Slovenijales "),
            new Sifrant(1512, "Ljubljana    Cankarjeva založba "),
            new Sifrant(1513, "Ljubljana    SKB banka "),
            new Sifrant(1514, "Ljubljana    Kompas "),
            new Sifrant(1516, "Ljubljana    Elektro Ljubljana "),
            new Sifrant(1517, "Ljubljana    Abanka Vipa "),
            new Sifrant(1518, "Ljubljana    Zavod za pokoj. in inval. zav. Slov. "),
            new Sifrant(1519, "Ljubljana    SPL Ljubljana "),
            new Sifrant(1520, "Ljubljana    Nova Ljubljanska banka "),
            new Sifrant(1521, "Ljubljana    Iskra invest "),
            new Sifrant(1522, "Ljubljana    Chemo "),
            new Sifrant(1523, "Ljubljana    Carinska uprava Republike Slovenije "),
            new Sifrant(1524, "Ljubljana    Carinarnica Ljubljana "),
            new Sifrant(1525, "Ljubljana    Klinični center Ljubljana "),
            new Sifrant(1526, "Ljubljana    Lek "),
            new Sifrant(1527, "Ljubljana    Petrol "),
            new Sifrant(1528, "Ljubljana    Emona "),
            new Sifrant(1529, "Ljubljana    Žito "),
            new Sifrant(1532, "Ljubljana    Salamonov oglasnik "),
            new Sifrant(1533, "Ljubljana    BTC "),
            new Sifrant(1534, "Ljubljana    Okrajno sodišče v Ljubljani "),
            new Sifrant(1535, "Ljubljana    Ministrstvo za promet "),
            new Sifrant(1536, "Ljubljana    Mladinska knjiga Založba "),
            new Sifrant(1537, "Ljubljana    Mobitel, d.d. "),
            new Sifrant(1538, "Ljubljana    DZS "),
            new Sifrant(1540, "Ljubljana    EPPS, Elektron. pismo Pošte Slov. "),
            new Sifrant(1542, "Ljubljana    KDD - Centralna klirinško depotna družba "),
            new Sifrant(1543, "Ljubljana    Športna loterija "),
            new Sifrant(1544, "Ljubljana    Kolinska "),
            new Sifrant(1545, "Ljubljana    Kanal A "),
            new Sifrant(1546, "Ljubljana    Telekom Slovenije "),
            new Sifrant(1547, "Ljubljana    Telekom Slovenije, PE Ljubljana "),
            new Sifrant(1550, "Ljubljana    RTV Slovenija "),
            new Sifrant(1600, "Ljubljana    Pošta Slovenije d.o.o., PE Ljubljana "),
            new Sifrant(1004, "Ljubljana - carinska pošta"),
            new Sifrant(1231, "Ljubljana - Črnuče"),
            new Sifrant(1261, "Ljubljana - Dobrunje"),
            new Sifrant(1260, "Ljubljana - Polje"),
            new Sifrant(1002, "Ljubljana - poštni center"),
            new Sifrant(1210, "Ljubljana - Šentvid"),
            new Sifrant(1211, "Ljubljana - Šmartno"),
            new Sifrant(3333, "Ljubno ob Savinji"),
            new Sifrant(9240, "Ljutomer"),
            new Sifrant(3215, "Loče"),
            new Sifrant(5231, "Log pod Mangartom"),
            new Sifrant(1358, "Log pri Brezovici"),
            new Sifrant(1370, "Logatec"),
            new Sifrant(1434, "Loka pri Zidanem Mostu"),
            new Sifrant(3223, "Loka pri Žusmu"),
            new Sifrant(6219, "Lokev"),
            new Sifrant(1318, "Loški Potok"),
            new Sifrant(2324, "Lovrenc na Dravskem polju"),
            new Sifrant(2344, "Lovrenc na Pohorju"),
            new Sifrant(3334, "Luče"),
            new Sifrant(1225, "Lukovica"),
            new Sifrant(9202, "Mačkovci"),
            new Sifrant(2322, "Majšperk"),
            new Sifrant(2321, "Makole"),
            new Sifrant(9243, "Mala Nedelja"),
            new Sifrant(2229, "Malečnik"),
            new Sifrant(6273, "Marezige"),
            new Sifrant(2508, "Maribor    Okrajno sodišče v Mariboru "),
            new Sifrant(2000, "Maribor"),
            new Sifrant(2001, "Maribor"),
            new Sifrant(2500, "Maribor    Pošta Slovenije d.o.o. "),
            new Sifrant(2501, "Maribor    Upravna enota Maribor "),
            new Sifrant(2502, "Maribor    Davčna uprava RS, izpostava Maribor "),
            new Sifrant(2503, "Maribor    Okrajno in okrožno sodišče v Mariboru "),
            new Sifrant(2504, "Maribor    Večer "),
            new Sifrant(2505, "Maribor    Nova Kreditna banka Maribor "),
            new Sifrant(2506, "Maribor    Henkel Slovenija "),
            new Sifrant(2507, "Maribor    Zavarovalnica Maribor "),
            new Sifrant(2509, "Maribor    Elektro Maribor "),
            new Sifrant(2600, "Maribor    Pošta Slovenije d.o.o., PE Maribor "),
            new Sifrant(2603, "Maribor    Pošta Slovenije d.o.o., Skladišče Maribor "),
            new Sifrant(2609, "Maribor    Pošta Slovenije d.o.o., Paketni ekspedit "),
            new Sifrant(2610, "Maribor    Pošta Slovenije d.o.o., Centralna RA pisarna "),
            new Sifrant(2607, "Maribor - center za digitalizacijo    Pošta Slovenije d.o.o. "),
            new Sifrant(2002, "Maribor - poštni center"),
            new Sifrant(2206, "Marjeta na Dravskem polju"),
            new Sifrant(2281, "Markovci"),
            new Sifrant(9221, "Martjanci"),
            new Sifrant(6242, "Materija"),
            new Sifrant(4211, "Mavčiče"),
            new Sifrant(1215, "Medvode"),
            new Sifrant(1234, "Mengeš"),
            new Sifrant(8330, "Metlika"),
            new Sifrant(2392, "Mežica"),
            new Sifrant(2204, "Miklavž na Dravskem polju"),
            new Sifrant(2275, "Miklavž pri Ormožu"),
            new Sifrant(5291, "Miren"),
            new Sifrant(8233, "Mirna"),
            new Sifrant(8216, "Mirna Peč"),
            new Sifrant(2382, "Mislinja"),
            new Sifrant(4281, "Mojstrana"),
            new Sifrant(8230, "Mokronog"),
            new Sifrant(1251, "Moravče"),
            new Sifrant(9226, "Moravske Toplice"),
            new Sifrant(5216, "Most na Soči"),
            new Sifrant(1221, "Motnik"),
            new Sifrant(3330, "Mozirje"),
            new Sifrant(9600, "Murska Sobota    Pošta Slovenije d.o.o., PE Murska Sobota "),
            new Sifrant(9501, "Murska Sobota    Mura "),
            new Sifrant(9000, "Murska Sobota"),
            new Sifrant(9001, "Murska Sobota"),
            new Sifrant(2366, "Muta"),
            new Sifrant(4202, "Naklo"),
            new Sifrant(4501, "Naklo    Merkur "),
            new Sifrant(3331, "Nazarje"),
            new Sifrant(1357, "Notranje Gorice"),
            new Sifrant(3203, "Nova Cerkev"),
            new Sifrant(5000, "Nova Gorica"),
            new Sifrant(5001, "Nova Gorica"),
            new Sifrant(5600, "Nova Gorica    Pošta Slovenije d.o.o., PE Nova Gorica "),
            new Sifrant(8600, "Nova mesto    Pošta Slovenije d.o.o., PE Novo mesto "),
            new Sifrant(1385, "Nova vas"),
            new Sifrant(8501, "Novo mesto    Krka "),
            new Sifrant(8000, "Novo mesto"),
            new Sifrant(8001, "Novo mesto"),
            new Sifrant(6243, "Obrov"),
            new Sifrant(9233, "Odranci"),
            new Sifrant(2317, "Oplotnica"),
            new Sifrant(2312, "Orehova vas"),
            new Sifrant(2270, "Ormož"),
            new Sifrant(1316, "Ortnek"),
            new Sifrant(1337, "Osilnica"),
            new Sifrant(8222, "Otočec"),
            new Sifrant(2361, "Ožbalt"),
            new Sifrant(2231, "Pernica"),
            new Sifrant(2211, "Pesnica pri Mariboru"),
            new Sifrant(9203, "Petrovci"),
            new Sifrant(3301, "Petrovče"),
            new Sifrant(6330, "Piran/Pirano"),
            new Sifrant(8255, "Pišece"),
            new Sifrant(6257, "Pivka"),
            new Sifrant(6232, "Planina"),
            new Sifrant(3225, "Planina pri Sevnici"),
            new Sifrant(6276, "Pobegi"),
            new Sifrant(8312, "Podbočje"),
            new Sifrant(5243, "Podbrdo"),
            new Sifrant(3254, "Podčetrtek"),
            new Sifrant(2273, "Podgorci"),
            new Sifrant(6216, "Podgorje"),
            new Sifrant(2381, "Podgorje pri Slovenj Gradcu"),
            new Sifrant(6244, "Podgrad"),
            new Sifrant(1414, "Podkum"),
            new Sifrant(2286, "Podlehnik"),
            new Sifrant(5272, "Podnanos"),
            new Sifrant(4244, "Podnart"),
            new Sifrant(3241, "Podplat"),
            new Sifrant(3257, "Podsreda"),
            new Sifrant(2363, "Podvelka"),
            new Sifrant(2208, "Pohorje"),
            new Sifrant(2257, "Polenšak"),
            new Sifrant(1355, "Polhov Gradec"),
            new Sifrant(4223, "Poljane nad Škofjo Loko"),
            new Sifrant(2319, "Poljčane"),
            new Sifrant(1272, "Polšnik"),
            new Sifrant(3313, "Polzela"),
            new Sifrant(3232, "Ponikva"),
            new Sifrant(6320, "Portorož/Portorose"),
            new Sifrant(6230, "Postojna"),
            new Sifrant(2331, "Pragersko"),
            new Sifrant(3312, "Prebold"),
            new Sifrant(4205, "Preddvor"),
            new Sifrant(6255, "Prem"),
            new Sifrant(1352, "Preserje"),
            new Sifrant(6258, "Prestranek"),
            new Sifrant(2391, "Prevalje"),
            new Sifrant(3262, "Prevorje"),
            new Sifrant(1276, "Primskovo"),
            new Sifrant(3253, "Pristava pri Mestinju"),
            new Sifrant(9207, "Prosenjakovci/Partosfalva"),
            new Sifrant(5297, "Prvačina"),
            new Sifrant(2250, "Ptuj"),
            new Sifrant(2323, "Ptujska Gora"),
            new Sifrant(9201, "Puconci"),
            new Sifrant(2327, "Rače"),
            new Sifrant(1433, "Radeče"),
            new Sifrant(9502, "Radenci    Radenska - Zdravilišče "),
            new Sifrant(9252, "Radenci"),
            new Sifrant(2360, "Radlje ob Dravi"),
            new Sifrant(1235, "Radomlje"),
            new Sifrant(4240, "Radovljica"),
            new Sifrant(8274, "Raka"),
            new Sifrant(1381, "Rakek"),
            new Sifrant(4283, "Rateče - Planica"),
            new Sifrant(2390, "Ravne na Koroškem"),
            new Sifrant(9246, "Razkrižje"),
            new Sifrant(3332, "Rečica ob Savinji"),
            new Sifrant(5292, "Renče"),
            new Sifrant(1310, "Ribnica"),
            new Sifrant(2364, "Ribnica na Pohorju"),
            new Sifrant(3272, "Rimske Toplice"),
            new Sifrant(1314, "Rob"),
            new Sifrant(5215, "Ročinj"),
            new Sifrant(3250, "Rogaška Slatina"),
            new Sifrant(9262, "Rogašovci"),
            new Sifrant(3252, "Rogatec"),
            new Sifrant(1373, "Rovte"),
            new Sifrant(2342, "Ruše"),
            new Sifrant(1282, "Sava"),
            new Sifrant(6333, "Sečovlje/Sicciole"),
            new Sifrant(4227, "Selca"),
            new Sifrant(2352, "Selnica ob Dravi"),
            new Sifrant(8333, "Semič"),
            new Sifrant(8281, "Senovo"),
            new Sifrant(6224, "Senožeče"),
            new Sifrant(8290, "Sevnica"),
            new Sifrant(6210, "Sežana"),
            new Sifrant(2214, "Sladki vrh"),
            new Sifrant(5283, "Slap ob Idrijci"),
            new Sifrant(2380, "Slovenj Gradec"),
            new Sifrant(2310, "Slovenska Bistrica"),
            new Sifrant(3210, "Slovenske Konjice"),
            new Sifrant(1216, "Smlednik"),
            new Sifrant(5232, "Soča"),
            new Sifrant(1317, "Sodražica"),
            new Sifrant(3335, "Solčava"),
            new Sifrant(5250, "Solkan"),
            new Sifrant(4229, "Sorica"),
            new Sifrant(4225, "Sovodenj"),
            new Sifrant(5281, "Spodnja Idrija"),
            new Sifrant(2241, "Spodnji Duplek"),
            new Sifrant(9245, "Spodnji Ivanjci"),
            new Sifrant(2277, "Središče ob Dravi"),
            new Sifrant(4267, "Srednja vas v Bohinju"),
            new Sifrant(8256, "Sromlje"),
            new Sifrant(5224, "Srpenica"),
            new Sifrant(1242, "Stahovica"),
            new Sifrant(1332, "Stara Cerkev"),
            new Sifrant(8342, "Stari trg ob Kolpi"),
            new Sifrant(1386, "Stari trg pri Ložu"),
            new Sifrant(2205, "Starše"),
            new Sifrant(2289, "Stoperce"),
            new Sifrant(8322, "Stopiče"),
            new Sifrant(3206, "Stranice"),
            new Sifrant(8351, "Straža"),
            new Sifrant(1313, "Struge"),
            new Sifrant(8293, "Studenec"),
            new Sifrant(8331, "Suhor"),
            new Sifrant(2353, "Sv. Duh na Ostrem Vrhu"),
            new Sifrant(2233, "Sveta Ana v Slovenskih goricah"),
            new Sifrant(2235, "Sveta Trojica v Slovenskih goricah"),
            new Sifrant(9244, "Sveti Jurij ob Ščavnici"),
            new Sifrant(3264, "Sveti Štefan"),
            new Sifrant(2258, "Sveti Tomaž"),
            new Sifrant(9204, "Šalovci"),
            new Sifrant(5261, "Šempas"),
            new Sifrant(5290, "Šempeter pri Gorici"),
            new Sifrant(3311, "Šempeter v Savinjski dolini"),
            new Sifrant(4208, "Šenčur"),
            new Sifrant(2212, "Šentilj v Slovenskih goricah"),
            new Sifrant(8297, "Šentjanž"),
            new Sifrant(2373, "Šentjanž pri Dravogradu"),
            new Sifrant(8310, "Šentjernej"),
            new Sifrant(3230, "Šentjur"),
            new Sifrant(3271, "Šentrupert"),
            new Sifrant(8232, "Šentrupert"),
            new Sifrant(1296, "Šentvid pri Stični"),
            new Sifrant(8275, "Škocjan"),
            new Sifrant(6281, "Škofije"),
            new Sifrant(4220, "Škofja Loka"),
            new Sifrant(3211, "Škofja vas"),
            new Sifrant(1291, "Škofljica"),
            new Sifrant(6274, "Šmarje"),
            new Sifrant(1293, "Šmarje - Sap"),
            new Sifrant(3240, "Šmarje pri Jelšah"),
            new Sifrant(8220, "Šmarješke Toplice"),
            new Sifrant(2315, "Šmartno na Pohorju"),
            new Sifrant(3341, "Šmartno ob Dreti"),
            new Sifrant(3327, "Šmartno ob Paki"),
            new Sifrant(1275, "Šmartno pri Litiji"),
            new Sifrant(2383, "Šmartno pri Slovenj Gradcu"),
            new Sifrant(3201, "Šmartno v Rožni dolini"),
            new Sifrant(3325, "Šoštanj"),
            new Sifrant(6222, "Štanjel"),
            new Sifrant(3220, "Štore"),
            new Sifrant(3304, "Tabor"),
            new Sifrant(3221, "Teharje"),
            new Sifrant(9251, "Tišina"),
            new Sifrant(5220, "Tolmin"),
            new Sifrant(3326, "Topolšica"),
            new Sifrant(2371, "Trbonje"),
            new Sifrant(1420, "Trbovlje"),
            new Sifrant(8231, "Trebelno"),
            new Sifrant(8210, "Trebnje"),
            new Sifrant(5252, "Trnovo pri Gorici"),
            new Sifrant(2254, "Trnovska vas"),
            new Sifrant(1222, "Trojane"),
            new Sifrant(1236, "Trzin"),
            new Sifrant(4290, "Tržič"),
            new Sifrant(8295, "Tržišče"),
            new Sifrant(1311, "Turjak"),
            new Sifrant(9224, "Turnišče"),
            new Sifrant(8323, "Uršna sela"),
            new Sifrant(1252, "Vače"),
            new Sifrant(3320, "Velenje"),
            new Sifrant(3322, "Velenje"),
            new Sifrant(3503, "Velenje    Gorenje "),
            new Sifrant(3504, "Velenje    ERA "),
            new Sifrant(8212, "Velika Loka"),
            new Sifrant(2274, "Velika Nedelja"),
            new Sifrant(9225, "Velika Polana"),
            new Sifrant(1315, "Velike Lašče"),
            new Sifrant(8213, "Veliki Gaber"),
            new Sifrant(9241, "Veržej"),
            new Sifrant(1312, "Videm - Dobrepolje"),
            new Sifrant(2284, "Videm pri Ptuju"),
            new Sifrant(8344, "Vinica"),
            new Sifrant(5271, "Vipava"),
            new Sifrant(4212, "Visoko"),
            new Sifrant(1294, "Višnja Gora"),
            new Sifrant(3205, "Vitanje"),
            new Sifrant(2255, "Vitomarci"),
            new Sifrant(1217, "Vodice"),
            new Sifrant(3212, "Vojnik"),
            new Sifrant(5293, "Volčja Draga"),
            new Sifrant(2232, "Voličina"),
            new Sifrant(3305, "Vransko"),
            new Sifrant(6217, "Vremski Britof"),
            new Sifrant(1360, "Vrhnika"),
            new Sifrant(2365, "Vuhred"),
            new Sifrant(2367, "Vuzenica"),
            new Sifrant(8292, "Zabukovje"),
            new Sifrant(1410, "Zagorje ob Savi"),
            new Sifrant(1303, "Zagradec"),
            new Sifrant(2283, "Zavrč"),
            new Sifrant(8272, "Zdole"),
            new Sifrant(4201, "Zgornja Besnica"),
            new Sifrant(2242, "Zgornja Korena"),
            new Sifrant(2201, "Zgornja Kungota"),
            new Sifrant(2316, "Zgornja Ložnica"),
            new Sifrant(2314, "Zgornja Polskava"),
            new Sifrant(2213, "Zgornja Velka"),
            new Sifrant(4247, "Zgornje Gorje"),
            new Sifrant(4206, "Zgornje Jezersko"),
            new Sifrant(2285, "Zgornji Leskovec"),
            new Sifrant(1432, "Zidani Most"),
            new Sifrant(3214, "Zreče"),
            new Sifrant(4209, "Žabnica"),
            new Sifrant(3310, "Žalec"),
            new Sifrant(4228, "Železniki"),
            new Sifrant(2287, "Žetale"),
            new Sifrant(4226, "Žiri"),
            new Sifrant(4274, "Žirovnica"),
            new Sifrant(8360, "Žužember"),
        };

    }
}