//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.ocenas = new HashSet<ocena>();
            this.studentinpredmets = new HashSet<studentinpredmet>();
            this.vpis = new HashSet<vpi>();
        }
    
        public int vpisnaStevilka { get; set; }
        public string ime { get; set; }
        public string priimek { get; set; }
        public System.DateTime datumRojstva { get; set; }
        public string krajRojstva { get; set; }
        public int obcinaRojstva { get; set; }
        public int drzavaRojstva { get; set; }
        public int spol { get; set; }
        public int drzavljanstvo { get; set; }
        public string emso { get; set; }
        public Nullable<int> davcnaStevilka { get; set; }
        public string email { get; set; }
        public string prenosniTelefon { get; set; }
        public string naslov { get; set; }
        public Nullable<bool> vrocanje { get; set; }
        public int postnaStevilka { get; set; }
        public int obcina { get; set; }
        public int drzava { get; set; }
        public string naslovZacasni { get; set; }
        public Nullable<bool> vrocanjeZacasni { get; set; }
        public Nullable<int> postnaStevilkaZacasni { get; set; }
        public Nullable<int> obcinaZacasni { get; set; }
        public Nullable<int> drzavaZacasni { get; set; }
        public int userId { get; set; }
    
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual ICollection<ocena> ocenas { get; set; }
        public virtual sifrant_drzava sifrant_drzava { get; set; }
        public virtual sifrant_drzava sifrant_drzava1 { get; set; }
        public virtual sifrant_drzava sifrant_drzava2 { get; set; }
        public virtual sifrant_drzava sifrant_drzava3 { get; set; }
        public virtual sifrant_obcina sifrant_obcina { get; set; }
        public virtual sifrant_obcina sifrant_obcina1 { get; set; }
        public virtual sifrant_obcina sifrant_obcina2 { get; set; }
        public virtual sifrant_postnastevilka sifrant_postnastevilka { get; set; }
        public virtual sifrant_postnastevilka sifrant_postnastevilka1 { get; set; }
        public virtual sifrant_spol sifrant_spol { get; set; }
        public virtual ICollection<studentinpredmet> studentinpredmets { get; set; }
        public virtual ICollection<vpi> vpis { get; set; }
        public virtual zeton zeton { get; set; }
    }
}
