//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.predmets = new HashSet<predmet>();
            this.ocenas = new HashSet<ocena>();
            this.vpisnilists = new HashSet<vpisnilist>();
        }
    
        public int vpisna_stevilka { get; set; }
        public string ime { get; set; }
        public string priimek { get; set; }
        public string naslov { get; set; }
        public string datum_rojstva { get; set; }
        public string spol { get; set; }
        public int userId { get; set; }
        public string kraj_rojstva { get; set; }
        public Nullable<int> obcinaRojstva { get; set; }
        public Nullable<int> drzavaRojstva { get; set; }
        public Nullable<int> drzavljanstvo { get; set; }
        public string emso { get; set; }
        public Nullable<int> davcnaStevilka { get; set; }
        public string email { get; set; }
        public string prenosniTelefon { get; set; }
        public Nullable<int> postnaStevilka { get; set; }
        public Nullable<int> obcina { get; set; }
        public Nullable<int> drzava { get; set; }
        public string naslovZacasni { get; set; }
        public Nullable<bool> vrocanjeZacasni { get; set; }
        public Nullable<int> postnaStevilkaZacasni { get; set; }
        public Nullable<int> obcinaZacasni { get; set; }
        public Nullable<int> drzavaZacasni { get; set; }
    
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual ICollection<predmet> predmets { get; set; }
        public virtual ICollection<ocena> ocenas { get; set; }
        public virtual ICollection<vpisnilist> vpisnilists { get; set; }
    }
}
