//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tocke
    {
        public int id { get; set; }
        public int tocke1 { get; set; }
        public long prijavaId { get; set; }
    
        public virtual prijavanaizpit prijavanaizpit { get; set; }
    }
}
