//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uporabnik
    {
        public uporabnik()
        {
            this.ip_zaklep = new HashSet<ip_zaklep>();
        }
    
        public long id { get; set; }
        public string email { get; set; }
        public string geslo { get; set; }
        public Nullable<long> napacne_prijave { get; set; }
    
        public virtual ICollection<ip_zaklep> ip_zaklep { get; set; }
    }
}
