//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpisnilist
    {
        public int id { get; set; }
        public string studijskoLeto { get; set; }
        public Nullable<int> vpisnaStevilka { get; set; }
        public string priimek { get; set; }
        public System.DateTime datumRojstva { get; set; }
        public string krajRojstva { get; set; }
        public int obcinaRojstva { get; set; }
        public int drzavaRojstva { get; set; }
        public int drzavljanstvo { get; set; }
        public int spol { get; set; }
        public string emso { get; set; }
        public int davcnaStevilka { get; set; }
        public string email { get; set; }
        public string prenosniTelefon { get; set; }
        public string naslov { get; set; }
        public Nullable<bool> vrocanje { get; set; }
        public int postnaStevilka { get; set; }
        public int obcina { get; set; }
        public int drzava { get; set; }
        public string naslovZacasni { get; set; }
        public Nullable<bool> vrocanjeZacasni { get; set; }
        public Nullable<int> postnaStevilkaZacasni { get; set; }
        public Nullable<int> obcinaZacasni { get; set; }
        public Nullable<int> drzavaZacasni { get; set; }
        public int studijskiProgram { get; set; }
        public int smer { get; set; }
        public int krajIzvajanja { get; set; }
        public int izbirnaSkupina { get; set; }
        public Nullable<int> studijskiProgram2 { get; set; }
        public Nullable<int> smer2 { get; set; }
        public Nullable<int> krajIzvajanja2 { get; set; }
        public Nullable<int> izbirnaSkupina2 { get; set; }
        public int vrstaStudija { get; set; }
        public int vrstaVpisa { get; set; }
        public int letnikStudija { get; set; }
        public int nacinStudija { get; set; }
        public int oblikaStudija { get; set; }
        public Nullable<int> studijskoLetoPrvegaVpisa { get; set; }
        public Nullable<bool> soglasje1 { get; set; }
        public Nullable<bool> soglasje2 { get; set; }
        public bool potrjen { get; set; }
        public string ime { get; set; }
    
        public virtual student student { get; set; }
    }
}
