//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zeton
    {
        public int vpisnaStevilka { get; set; }
        public int letnik { get; set; }
        public bool porabljen { get; set; }
    
        public virtual student student { get; set; }
    }
}
